name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - orders/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: cd orders && echo -e "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env.local && docker build -t erwanriou/ticketshop_orders .
      - run: docker login -u  ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push erwanriou/ticketshop_orders
      - name: Configure deploy with digital ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment orders-depl
