name: tests-payments

on:
  pull_request:
    - "payment/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payment && echo -e "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}} \n@erwanriou:registry=https://npm.pkg.github.com/erwanriou \nregistry=https://registry.npmjs.org" > .npmrc && npm i && npm run test:ci
